# HW05 - Exploring Trees/Graphs

YOUR NAME: _James Nguyen_________________

In [2]:
# here is a list of edges:
T = [('Bob','Eve'),('Alice','Carol'),('Eve','Frank'),('Alice','Doug'),('Frank','Ginger'), \
         ('Eve','Howard'),('Carol','Irene'),('Frank','Jeff'),('Doug','Kathy'),('Bob','Luis'), \
         ('Alice','Bob'),('Bob','Mabel'),('Ginger','Norm'),('Howard','Oprah'),('Carol','Peter'), \
         ('Kathy','Queen'),('Mabel','Ursala'),('Luis','Ronald'),('Ginger','Sarah'),('Irene','Tom'), \
         ('Jeff','Vince'),('Peter','Wanda'),('Oprah','Xanthia'),('Norm','Yaakov'),('Luis','Zandra')]

print ('T has',len(T),'edges')
vertices = set()
for edge in T:
    s,t = edge
    vertices.add(s)
    vertices.add(t)
print ('T has',len(vertices),'vertices')

T has 25 edges
T has 26 vertices


So this could be a tree. Now lets compute the number of parents for each vertex. The result confirms that we indeed have a tree and that the root is Alice (right?).

In [4]:
np = {} # a dictionary that maps vertex to the number of incoming edges
for v in vertices:
    np[v] = 0
for parent,child in T:
    np[child] += 1
# for parent,child in T:
#     np[parent] += 1
print (np)

{'Frank': 1, 'Kathy': 1, 'Mabel': 1, 'Bob': 1, 'Irene': 1, 'Doug': 1, 'Eve': 1, 'Ursala': 1, 'Sarah': 1, 'Carol': 1, 'Wanda': 1, 'Peter': 1, 'Yaakov': 1, 'Oprah': 1, 'Jeff': 1, 'Howard': 1, 'Luis': 1, 'Queen': 1, 'Norm': 1, 'Ronald': 1, 'Vince': 1, 'Xanthia': 1, 'Tom': 1, 'Zandra': 1, 'Alice': 0, 'Ginger': 1}


We now construct a dictionary of pairs (p,c) where p is the parent of the list of children c

In [3]:
adjacency_map = {}
for v in vertices:
    adjacency_map[v] = []
for p,c in T:
    adjacency_map[p].append(c)
    #you can also do adjacency_map[c].append(p) to treat T as undirected edge list

print ("node and their children:")
for p in adjacency_map:
    print (p, ":", adjacency_map[p])

#print ()
print (adjacency_map)

node and their children:
Zandra : []
Vince : []
Yaakov : []
Howard : ['Oprah']
Alice : ['Carol', 'Doug', 'Bob']
Queen : []
Frank : ['Ginger', 'Jeff']
Sarah : []
Ronald : []
Xanthia : []
Mabel : ['Ursala']
Doug : ['Kathy']
Norm : ['Yaakov']
Peter : ['Wanda']
Oprah : ['Xanthia']
Bob : ['Eve', 'Luis', 'Mabel']
Irene : ['Tom']
Ginger : ['Norm', 'Sarah']
Kathy : ['Queen']
Tom : []
Ursala : []
Jeff : ['Vince']
Carol : ['Irene', 'Peter']
Wanda : []
Luis : ['Ronald', 'Zandra']
Eve : ['Frank', 'Howard']
{'Zandra': [], 'Vince': [], 'Yaakov': [], 'Howard': ['Oprah'], 'Alice': ['Carol', 'Doug', 'Bob'], 'Queen': [], 'Frank': ['Ginger', 'Jeff'], 'Sarah': [], 'Ronald': [], 'Xanthia': [], 'Mabel': ['Ursala'], 'Doug': ['Kathy'], 'Norm': ['Yaakov'], 'Peter': ['Wanda'], 'Oprah': ['Xanthia'], 'Bob': ['Eve', 'Luis', 'Mabel'], 'Irene': ['Tom'], 'Ginger': ['Norm', 'Sarah'], 'Kathy': ['Queen'], 'Tom': [], 'Ursala': [], 'Jeff': ['Vince'], 'Carol': ['Irene', 'Peter'], 'Wanda': [], 'Luis': ['Ronald', 'Zandra'], 

In [4]:
print (5*"Hello!")

Hello!Hello!Hello!Hello!Hello!


In [5]:
# A recursive depth-first traversal of a tree defined by an adjacency_map
def print_tree_depth_first(parent, adjacency_map, level=0):
    print (level*'  ', parent)
    children = adjacency_map[parent]
    for child in children:
        print_tree_depth_first(child, adjacency_map, level+1)

root = 'Alice'
print_tree_depth_first(root, adjacency_map)

 Alice
   Carol
     Irene
       Tom
     Peter
       Wanda
   Doug
     Kathy
       Queen
   Bob
     Eve
       Frank
         Ginger
           Norm
             Yaakov
           Sarah
         Jeff
           Vince
       Howard
         Oprah
           Xanthia
     Luis
       Ronald
       Zandra
     Mabel
       Ursala


## Question 1
extend the breadth-first traversal to include the generation, so that the output is like below. Do this by also storing the generation in the queue.

In [6]:
from collections import deque 
am={"A":["B","D","E"], "B":["C"], "E":["F"], "D":[], "F":[], "C":[]}
            
# breadth-first traversal using a queue
def print_tree_breadth_first(root, adjacency_map):
    Q = deque()
    Q.append(root)
    while len(Q)>0:
        p = Q.popleft()
        print (p)
        children = adjacency_map[p]
        for child in children:
            Q.append(child)
            
print_tree_breadth_first("A", am)

def print_tree_breadth_first_by_generation(root, adjacency_map):
    Q = deque()
    gen_num = 1
    Q.append(gen_num) # generation number
    Q.append(root)
    while len(Q)>0:
        p = Q.popleft()
        if isinstance(p, int):
            if gen_num <= p: # if new generation print endline, number, and increment gen_num
                print("")
                print(p, end=": ")
                gen_num += 1
            p = Q.popleft() # if not new generation then ignore generation number
        print (p, end=" ")
        children = adjacency_map[p]
        for child in children:
            Q.append(gen_num)
            Q.append(child)


print_tree_breadth_first_by_generation("Alice", adjacency_map)
#print_tree_breadth_first_by_generation("A", am)

A
B
D
E
C
F

1: Alice 
2: Carol Doug Bob 
3: Irene Peter Kathy Eve Luis Mabel 
4: Tom Wanda Queen Frank Howard Ronald Zandra Ursala 
5: Ginger Jeff Oprah 
6: Norm Sarah Vince Xanthia 
7: Yaakov 

## Question 2
Write a function that checks if for the given directed graph (given by a list of edges E) root is connected to every other vertex.

In [7]:
def all_connected_to(edge_list, root):
    """ return true if you can reach all nodes in the graph given
    by a list of edges (edge_list) from root """
    
    # start by constructing set of vertices and the adjacency map
    vertices = set()
    for edge in edge_list:
        s,t = edge
        vertices.add(s)
        vertices.add(t)
    #print(vertices)
        
    adjacency_map = {}
    for v in vertices:
        adjacency_map[v] = []
    for p,c in edge_list:
        adjacency_map[p].append(c)
    #print(adjacency_map)
    
    Q = deque()
    Q.append(root)
    while len(Q)>0:
        p = Q.popleft()
        #print (p)
        if p in vertices:
            vertices.remove(p)
        else:
            continue
        children = adjacency_map[p]
        for child in children:
            Q.append(child)
    #print(vertices)
    
    
    if len(vertices) > 0:
        return False
    else:
        return True
    

In [8]:
G = [("A","B"), ("B","C")]
print (all_connected_to(G, "A"))
G2 = [("1","2"), ("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G2, "A"))
print (all_connected_to(G2, "1"))
G3 = [("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G3, "C"))
# and our graph from above?
print (all_connected_to(T, "Alice"))

True
False
False
True
True


## Question 3
We now treat the the graph T from above as undirected (edges going in both directions) and construct a tree rooted in Bob. The tree will contain edges from a vertex to the parent and direct children. The result will tell us how far removed the vertices from our root Bob are.

In [9]:
root = 'Bob'

# construct adjacency for graph T:
adjacency_map = {}
for vertex in vertices:
    adjacency_map[vertex] = []
for edge in T:
    s,t = edge
    adjacency_map[s].append(t)
    adjacency_map[t].append(s)
    
#print ("parents/children of Ginger:", adjacency_map['Ginger'])
#print (adjacency_map)

# now create the adjacency map of the tree rooted in 'Bob'
tree = {}

#TODO: construct tree by using a queue

# Initialize the tree with 'Bob' as the root
tree = {'Bob': []}

queue = deque()
queue.append('Bob')

# Visited vertices
visited = set()
visited.add('Bob')

while queue:
    vertex = queue.popleft()

    # Iterate through neighbors of the current_vertex in the original graph
    for member in adjacency_map[vertex]:
        if member not in visited:
            # Add member as a child of the current vertex in the tree
            tree[vertex].append(member)
            # Create list for member key
            tree[member] = []
            # Mark member as visited and add to queue
            visited.add(member)
            queue.append(member)

print (tree)
#print_tree_depth_first('Bob', tree, level=0)

{'Bob': ['Eve', 'Luis', 'Alice', 'Mabel'], 'Eve': ['Frank', 'Howard'], 'Luis': ['Ronald', 'Zandra'], 'Alice': ['Carol', 'Doug'], 'Mabel': ['Ursala'], 'Frank': ['Ginger', 'Jeff'], 'Howard': ['Oprah'], 'Ronald': [], 'Zandra': [], 'Carol': ['Irene', 'Peter'], 'Doug': ['Kathy'], 'Ursala': [], 'Ginger': ['Norm', 'Sarah'], 'Jeff': ['Vince'], 'Oprah': ['Xanthia'], 'Irene': ['Tom'], 'Peter': ['Wanda'], 'Kathy': ['Queen'], 'Norm': ['Yaakov'], 'Sarah': [], 'Vince': [], 'Xanthia': [], 'Tom': [], 'Wanda': [], 'Queen': [], 'Yaakov': []}


Execute the following two blocks to check your result:

In [10]:
print_tree_depth_first(root, tree)

 Bob
   Eve
     Frank
       Ginger
         Norm
           Yaakov
         Sarah
       Jeff
         Vince
     Howard
       Oprah
         Xanthia
   Luis
     Ronald
     Zandra
   Alice
     Carol
       Irene
         Tom
       Peter
         Wanda
     Doug
       Kathy
         Queen
   Mabel
     Ursala


In [11]:
print_tree_breadth_first(root, tree)

Bob
Eve
Luis
Alice
Mabel
Frank
Howard
Ronald
Zandra
Carol
Doug
Ursala
Ginger
Jeff
Oprah
Irene
Peter
Kathy
Norm
Sarah
Vince
Xanthia
Tom
Wanda
Queen
Yaakov


## Question 4: n queens problem
Backtracking is the technique of recursively exploring the tree that contains all the possible solutions to a problem. Choose a systematic way to explore all the possible cases. This approach should reflect a rooted tree, and the backtracking approach is a depth-first search of the rooted tree. Whenever the search has found a solution or determined that there are no further solutions on the branches below the current vertex, backtrack to the preceeding vertex. 

A classic example of a problem that can be easily solved with this approach is the n queens problem.  This problem is to determine all the possible ways to place n nonattacking queens on an n-by-n chess board. The following code provides two helpful routines for this problem and illustrates one of the solutions for the 4 queens problem.

In [12]:
import numpy as np

def build_chessboard(N):
    chessboard = np.zeros((N,N))
    return chessboard

def print_chessboard(chessboard):
    N = len(chessboard)
    for r in range(N):
        for c in range(N):
#             if chessboard[r,c] == 1:
#                 print ('Q', end="")
#             else:
#                 print ('.', end="")
            if chessboard[r,c] == 1:
                print ('Q', end="")
            elif chessboard[r,c] == 2:
                print('X', end="")
            else:
                print ('.', end="")

        print ()
    print ()

# generate an empty 4x4 chessboard:
chessboard = build_chessboard(4)
print (chessboard)

# Place 4 non-attacking queens on this board
chessboard[1,0] = 1
chessboard[3,1] = 1
chessboard[0,2] = 1
chessboard[2,3] = 1

# Pretty print the resulting board
print_chessboard(chessboard)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
..Q.
Q...
...Q
.Q..



Complete the following code to solve the n queens problem by returning the total number of solutions while printing only the first five solutions.

In [13]:
def change_diagonal_values1(array, row, col, value):
    start_row = row
    start_col = col
    while start_row < len(array) and start_col < len(array):
        array[start_row, start_col] = value
        start_row += 1
        start_col += 1
        

def change_diagonal_values2(array, row, col, value):
    start_row = row
    start_col = col
    while start_row >= 0 and start_col >= 0:
        array[start_row, start_col] = value
        start_row -= 1
        start_col -= 1

def change_diagonal_values3(array, row, col, value):
    start_row = row
    start_col = col
    while start_row >= 0 and start_col < len(array):
        array[start_row, start_col] = value
        start_row -= 1
        start_col += 1

def change_diagonal_values4(array, row, col, value):
    start_row = row
    start_col = col
    while start_row < len(array) and start_col >= 0:
        array[start_row, start_col] = value
        start_row += 1
        start_col -= 1
    

In [14]:
def n_queens(chessboard, column=0, count=0):
    """ given a partially filled <chessboard>, try to place a queen in column <column> and recursively fill the board.
    Finally return the number of solutions (added to <count>)"""
    N = len(chessboard)
    if column == N:
        if count < 5:
            print("Reached the end!")
            print_chessboard(chessboard)
        return count + 1
    
    # Examine all available squares in column <column>, place the queen, and 
    # mark all squares under attack by that queen.
    # Note: you can make a copy of a chessboard using chessboard.copy()
    
    # TODO
    
    for row in range(N):
        if np.any(chessboard[row,column] > 0):
            continue
        else:
            updated_chessboard = chessboard.copy()
            change_diagonal_values1(updated_chessboard, row, column, 2)
            change_diagonal_values2(updated_chessboard, row, column, 2)
            change_diagonal_values3(updated_chessboard, row, column, 2)
            change_diagonal_values4(updated_chessboard, row, column, 2)
            updated_chessboard[row,:] = 2
            updated_chessboard[:,column] = 2
            updated_chessboard[row, column] = 1
            #print_chessboard(updated_chessboard)
            count = n_queens(updated_chessboard, column+1, count)
    return count

chessboard = build_chessboard(5)
count = n_queens(chessboard)
print ("solutions: ", count)

Reached the end!
QXXXX
XXXQX
XQXXX
XXXXQ
XXQXX

Reached the end!
QXXXX
XXQXX
XXXXQ
XQXXX
XXXQX

Reached the end!
XXQXX
QXXXX
XXXQX
XQXXX
XXXXQ

Reached the end!
XXXQX
QXXXX
XXQXX
XXXXQ
XQXXX

Reached the end!
XQXXX
XXXQX
QXXXX
XXQXX
XXXXQ

solutions:  10


In [15]:
# This example shows why .copy() is needed in your code above (reference semantics!)
def test(cb):
    cb[0,0]=1
    print_chessboard(cb)
    
chessboard = build_chessboard(4)
print_chessboard(chessboard)
test(chessboard.copy())# try chessboard.copy() instead
print_chessboard(chessboard)  # oooops!
test = chessboard.copy()


....
....
....
....

Q...
....
....
....

....
....
....
....



In [16]:
import copy

# copy makes a copy of the outer-most object, but keeps the same references to the inner
# object.
a=[2,4,[6]]
print ("before: a=", a)

#not copying:
a=[2,4,[6]]
b=a
b[0]+=1
b[2][0]+=3
print ("after:  a=",a," b=", b, " (not copying)")

# using copy:
a=[2,4,[6]]
b=copy.copy(a)
b[0]+=1
b[2][0]+=3
print ("after:  a=",a," b=", b, " (using copy)")

# deepcopy also makes a copy of each contained element (recursively)
a=[2,4,[6]]
b=copy.deepcopy(a)
b[0]+=1
b[2][0]+=3
print ("after:  a=",a," b=", b, " (using deepcopy)")

before: a= [2, 4, [6]]
after:  a= [3, 4, [9]]  b= [3, 4, [9]]  (not copying)
after:  a= [2, 4, [9]]  b= [3, 4, [9]]  (using copy)
after:  a= [2, 4, [6]]  b= [3, 4, [9]]  (using deepcopy)
