### Load in NumPy

In [2]:
import numpy as np

### The Basics

In [11]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) # remember to include extra brackets to create 2D array
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [9]:
# Get Shape(rows x columns)
print(b.shape)

(2, 3)


In [12]:
# Get Type
print(a.dtype)

int16


In [14]:
# Get Size (in bytes)
a.itemsize

2

In [15]:
# Get Total Size (number of elements) 
a.size

3

### Accessing/Changing specific elements, rows, columns, etc.

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# Get a specific element [r,c]
print(a[1, 5])
print(a[1,-2])

13
13


In [19]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]
a[0,1:-1:2]

array([2, 4, 6])

In [24]:
a[1,5] = 20
print(a,'\n')

a[:,2] = 5
print(a,'\n')

a[:,2] = [1,2]
print(a,'\n')

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]] 

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]] 

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]] 



In [25]:
# 3D example (think of as container of 2D matrices)
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
        

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# Get specific element (work outside in)
b[0,1,1]

4

In [28]:
# replace
b[:,1,:]= [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [30]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [34]:
# Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [38]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [40]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.65142237, 0.97890785],
       [0.39023251, 0.95368474],
       [0.22345426, 0.88409495],
       [0.310867  , 0.0991048 ]])

In [41]:
# Random numbers full_like
np.random.random_sample(a.shape)

array([[0.59284099, 0.75296926, 0.7074783 , 0.64030735, 0.42484962,
        0.35014287, 0.85275309],
       [0.64800876, 0.04776556, 0.99251816, 0.38003617, 0.27540704,
        0.70652722, 0.85048611]])

In [10]:
# Random Integer Values
np.random.randint(3, size=(3,3))

array([[1, 0, 2],
       [1, 2, 2],
       [1, 0, 0]])

In [6]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
array = np.ones((5,5))
size = array.shape
print(array,'\n')

z = np.zeros((3,3))
z[1,1] = 9

array[1:4,1:4] = z
print(array, '\n')



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 



### Be careful when copying arrays!!!

In [61]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a) # when setting them equal, the pointers are made equal so all changes to b affect a

[100   2   3]


In [62]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


### Mathematics

In [63]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [64]:
a+2

array([3, 4, 5, 6])

In [65]:
a*2

array([2, 4, 6, 8])

In [66]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [67]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [68]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [69]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [70]:
# cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [71]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [74]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

c = np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [75]:
# Find the determinant
np.linalg.det(c)

0.0

In [76]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [77]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.min(stats, axis=1) # axis = 0 means columns, axis = 1 means rows

array([1, 4])

In [79]:
np.max(stats)

6

In [81]:
np.sum(stats)

21

In [82]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, '\n')

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [85]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Load Data From File

In [89]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [91]:
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced Indexing

In [92]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [93]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [94]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [95]:
np.any(filedata > 50, axis=0) # axis=0 means columns, axis=1 means rows

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [96]:
np.all(filedata > 50, axis=0) # axis=0 means columns, axis=1 means rows

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [98]:
((filedata > 50) & (filedata < 100)) # greater than 50 but less than 100

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [99]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])